### ISSUE TITLE
Rules for incoming calls

### ISSUE THREAD

**Issue by Nikonok80** [aj3423/SpamBlocker#117]
Hi there!

I've set up the rules for incoming calls using the Whitelist. Now, I want to configure the settings to receive calls from contacts in my phone book and numbers on the whitelist. All other calls should be automatically rejected.

Could you please advise on the necessary settings for this?
![photo_5352793152773284876_y](https://github.com/user-attachments/assets/265897fe-ddf3-429f-a582-fca829c09e60)

**Comment by krystofair** [comment]
I using it partly in that way, not using whitelist.
I've read some code, done some tests, and claim that **it should be enough for you to click this button in line of "contact" to display "Exclusive" (in english) should be in red color**.
Because then rule of contact change priority to 0 (zero) and numbers from whitelist will be checked first. So when whitelist match, contact will skip, or if whitelist not match, contact list will be checked to reject or allow that call.

@aj3423 awesome app!❤️

**Comment by aj3423** [comment]
@krystofair Thanks for the explanation, it's absolutely correct.

@Nikonok80 An equivalent way is to add a blacklist rule `.*` with priority 0:

Exclusive Contact 
  ==
Inclusive Contact  
  + 
Blacklist rule .* (priority 0)


You can verify that with the "Test" feature.

**Comment by Nikonok80** [comment]
@aj3423
@krystofair
Thanks, I did as you wrote. I still don't quite understand how to work with priorities.

**Comment by aj3423** [comment]
It will pick the matched rule that has highest priority.

For example, when multiple rules are defined:

 1. Contact Inclusive (priority 10)
 2. Blacklist `.*` (priority 0)
 3. Whitelist `790030.*` (priority 1)

A call from:
- non-contact:  matches 2, so it will be blocked
- contact: matches both 1 and 2, it will be allowed by 1 because it has higher priority (10 > 0)
- number 790030, matches 2 and 3, will be allowed by 3 (priority 1 > 0)
