### ISSUE TITLE
Pass? I was hoping not to see calls not in contacts

### ISSUE THREAD

**Issue by GorillaDaddy** [aj3423/SpamBlocker#13]
![Screenshot_20240426-161954](https://github.com/aj3423/SpamBlocker/assets/30662497/feeae356-55b9-4b86-bbf5-de5905f893f7)
![Screenshot_20240426-165217](https://github.com/aj3423/SpamBlocker/assets/30662497/90c907c0-f75f-45bc-bb28-7a91f8bd4121)

Pixel 5, all permissions granted. Phone rings on spam. Maybe I am doing something wrong.

**Comment by aj3423** [comment]
The default logic is "Inclusive", I'll add an option "Exclusive" later.

The logic will be:

Switch off: contact checking is disabled, incoming call/text will be checked by other rules
Switch on: contacts are permitted
  -  Incusive: non-contacts are checked by other rules
  -  Exclusive: non-contacts are blocked

Currently, as a workaround, you can add a number rule `.*`, mark it as "non contact" in description(optional), it's the same behavior as "Exclusive".

**Comment by GorillaDaddy** [comment]
![image](https://github.com/aj3423/SpamBlocker/assets/30662497/ddc06f1c-ecf4-4540-a6ed-d942be53ad98)

Like this? Admittedly, I'm a little confused, "Allow contacts" says to to permit a call. And that this is prior to the filters below.  So blacklisting all numbers afterwards suggests that the call which was previously permitted, will get blocked. What does "priority" do? Does that "1" actually put the blacklist filter for all numbers before the "Allow contacts"?

**Comment by aj3423** [comment]
Yeah, the rule `.*` in the above image should work.


"Prior to other filters below" means if it's enabled, a call from contact will always pass, doesn't matter if the number matches any blocking rule in number filters. This logic will be improved later, all of the Contact/Repeated/RecentApp will have a priority as 10. Because currently there is no way to block a spam if it's from a contact, or it calls you twice and the RepeatedCall is enabled. With the new logic, you can set a number rule with priority 11 to always block that spam number.

BTW, try this action build: https://github.com/aj3423/SpamBlocker/actions/runs/8857903749, it supports testing rules directly within the app, no need to wait for a new call. And I added more detailed tooltip for the Contact:
- When enabled, calls/texts from contacts are permitted.
- When disabled, calls/texts will still be checked by other rules.
    If you want to block all non-contact calls/texts, enable this and add a number rule: .*

**Comment by GorillaDaddy** [comment]
Working great now, latest 1.4; thanks!


![image](https://github.com/aj3423/SpamBlocker/assets/30662497/187c97bd-1474-45fa-92f3-1362e0c00e38)

**Comment by aj3423** [comment]
Now for Contacts functionality, there are two modes Inclusive/Exclusive , the Exclusive mode blocks non-contacts by default, same behavior as Incusive + blocking `.*`

The action build: https://github.com/aj3423/SpamBlocker/actions/runs/8934899159, btw, you can upgrade to this directly , no need to uninstall first.
