### ISSUE TITLE
Search number Phone in google

### ISSUE THREAD

**Issue by dayvydrn** [aj3423/SpamBlocker#148]
Suggestion: implement a search through Google to try to identify what is spam or redirect directly to Google passing the phone number as a query (parameter)

**Comment by aj3423** [comment]
Previously I had similar idea, query a third party database, such as [TrueCaller](https://www.truecaller.com/reverse-phone-number-lookup) and [Robokiller](https://lookup.robokiller.com), but I suppose after a couple of queries there will be the "human verification". 
Some may provide an API key,  if you paid for that key, you can use it in the query parameter to avoid those limitations. But in that case, I think, since the user rely so much on that database, he would've been using their own app. So I gave up on that idea.

But I've never thought about searching on Google. I tried these queries and got tons of unrelated information. 

 - the number only
 - something like: "is this a spam number? 1234567890"

**Comment by hayvan96** [comment]
What about the "should I answer" database ? Yet Another Call Blocker (https://gitlab.com/xynngh/YetAnotherCallBlocker) uses it, not sure though how the database is accessed. It's here https://gitlab.com/xynngh/YetAnotherCallBlocker_data but not obvious how the SIA db is incrementally added to that base.

**Comment by aj3423** [comment]
@hayvan96 
The SIA database is mysterious to me as well, but it's proprietary to YACB, I can't integrate it unless they made it public.

**Comment by dayvydrn** [comment]
Search in apps: telegram, whatsapp and others (display list of options).  In google search the first 3 results on the first page.

**Comment by aj3423** [comment]
> Search in apps: telegram, whatsapp and others (display list of options). 

Technically impossible.

>  In google search the first 3 results on the first page.

I don't see Google shows anything useful, can you show me a screenshot about the top three results?

**Comment by hayvan96** [comment]
> @hayvan96 The SIA database is mysterious to me as well, but it's proprietary to YACB, I can't integrate it unless they made it public.

According to YACB, it's "borrowed without asking" and, as far as I can see, not updated for 3 years now. So I guess there's no official API.

**Comment by aj3423** [comment]
As I understand, those spam numbers are contributed by the users, they cannot directly commit them to the data repository, there must be a server gathering those numbers, packing and uploading them to the data repository periodically. 

So I guess the data repository is just a snapshot for downloading the initial database, the incremental numbers are downloaded from the real server, that's why it may still work fine.

Anyway, I don't think they would make it public for any rival app, that would decrease their user base and in turn decrease their crowd-sourced numbers.

**Comment by morfikov** [comment]
YACB uses [this database](https://odebractelefon.pl). The database supports multiple countries. I wanted to switch from YACB to SpamBlocker, but the default phoneblock.net doesn't seem to have the Polish phone numbers). Is there is a way to make SpamBlocker work with this odebractelefon.pl website or its database, I mean, [here's an example of a spam call](https://www.odebractelefon.pl/numer-telefonu/451405560)

**Comment by aj3423** [comment]
@morfikov 

Typically, you need to setup following fields when customizing a query API.

1. Negative identifier (required)
2. Positive identifier (optional)
3. Category identifier (optional)


Here's how to do that:
1. Use `curl https://www.odebractelefon.pl/numer-telefonu/451405560` to get the response, it looks like:

```
...
	NEGATYWNA TELEMARKETER   </span>         <---- category
...
				<div class="ratings">
		<h2>451405560 Recenzje</h2>
		<ul>
			<li class='active'>16x negatywna</li>   </ul>       <---- negative identifier
...
```


2. This is the negative signature:

> 16x negatywna

  So the identifier is `\dx negatywna`. (the number will be identified as spam if this pattern is found in the response text)

3. The category signature is:

> NEGATYWNA TELEMARKETER

  So the identifier is `NEGATYWNA ([A-Z]+)`, the category will be extracted as "TELEMARKETER".

4. You can add Positive identifier accordingly.

Here's the full template, you can import it directly:

```json
{
    "id": 1,
    "desc": "SIA Poland",
    "actions": [
        {
            "type": "ParseIncomingNumber",
            "numberFilter": "[^+]\\d+"
        },
        {
            "type": "HttpDownload",
            "method": 0,
            "url": "https://www.odebractelefon.pl/numer-telefonu/{domestic}",
            "header": "",
            "body": ""
        },
        {
            "type": "ParseQueryResult",
            "negativeSig": "\\dx negatywna",
            "negativeFlags": 5,
            "positiveSig": "",
            "positiveFlags": 5,
            "categorySig": "NEGATYWNA ([A-Z]+)",
            "categoryFlags": 1029
        },
        {
            "type": "FilterSpamResult"
        },
        {
            "type": "ImportToSpamDB",
            "importReason": "Manually"
        }
    ],
    "enabled": true
}
```

This part:
> "numberFilter": "[^+]\\d+"

It means only check domestic numbers, international numbers will be skipped, since that site only works for poland numbers.

**Comment by morfikov** [comment]
It seems the solutions is working. I have to wait for some spam calls to see whether it does what it should in real time. :)

**Comment by aj3423** [comment]
@morfikov This is their global entry:
https://www.shouldianswer.net/search?q=+48451405560

The tricky thing is, they use different domains/languages for diffrernt country codes, that requires collecting all the signature translations.

BTW, there are both workflow testing and global testing, you don't have to wait for a real call.

**Comment by hayvan96** [comment]
Actually, I've tried the Polish spam example above, the website suggests me to go to https://www.doisjerepondre.fr/ (I'm in France).
But when I test the same +48XXXX spam number on the French website, the result leads back to the Polish website.

As the script per country seems quite easy to infer from the curl command above, we could contribute by sharing the national scripts (SIA Poland, SIA France) somewhere on the wiki ?

**Comment by aj3423** [comment]
> As the script per country seems quite easy to infer from the curl command above, we could contribute by sharing the national scripts (SIA Poland, SIA France) somewhere on the wiki ?

@hayvan96 That'll be nice, there's a guide for this: https://github.com/aj3423/SpamBlocker/issues/249

**Comment by hayvan96** [comment]
Well, I've tried this:
`
{
    "id": 1,
    "desc": "SIA France",
    "actions": [
        {
            "type": "ParseIncomingNumber",
            "numberFilter": "[^+]\\d+"
        },
        {
            "type": "HttpDownload",
            "method": 0,
            "url": "https://www.doisjerepondre.fr/numero-de-telephone/{domestic}",
            "header": "",
            "body": ""
        },
        {
            "type": "ParseQueryResult",
            "negativeSig": "\\dx négative",
            "negativeFlags": 5,
            "positiveSig": "",
            "positiveFlags": 5,
            "categorySig": "NéGATIVE ([A-Z]+)",
            "categoryFlags": 1029
        },
        {
            "type": "FilterSpamResult"
        },
        {
            "type": "ImportToSpamDB",
            "importReason": "Manually"
        }
    ],
    "enabled": true
}

The problem is that when I test 0681710269 (https://www.doisjerepondre.fr/numero-de-telephone/0681710269), I can see in the testing window that https://www.doisjerepondre.fr/numero-de-telephone/681710269 is requested, withtout the trailing 0. This leads to an error page, and the number passes through, while it should be stopped. 

What should I change in the code above? Thanks !
`

**Comment by aj3423** [comment]
The site expects the number to be either of `+cc...` or `0...`
There urls should work:
```
"url": "https://www.doisjerepondre.fr/numero-de-telephone/+33{domestic}"
```
or
```
"url": "https://www.doisjerepondre.fr/numero-de-telephone/0{domestic}"
```

**Comment by hayvan96** [comment]
> The site expects the number to be either of `+cc...` or `0...` There urls should work:
> 
> ```
> "url": "https://www.doisjerepondre.fr/numero-de-telephone/+33{domestic}"
> ```
> 
> or
> 
> ```
> "url": "https://www.doisjerepondre.fr/numero-de-telephone/0{domestic}"
> ```

Yes I had succeeded in requesting the right URL with 0{domestic}
However, when testing with a spam number, I get HTTP: <null>: and it passes through

**Comment by aj3423** [comment]
> However, when testing with a spam number, I get HTTP: : and it passes through

Can you show me the resolved url in the testing dialog?

![Image](https://github.com/user-attachments/assets/ca7c22fb-b8c6-4ec4-b941-670260110328)

**Comment by hayvan96** [comment]
> > However, when testing with a spam number, I get HTTP: : and it passes through
> 
> Can you show me the resolved url in the testing dialog?
> 
> ![Image](https://github.com/user-attachments/assets/ca7c22fb-b8c6-4ec4-b941-670260110328)

The error was due to the fact no internet access permission was granted. I'm adding the template to the wiki, as it seems to be working when testing.

I think that even domestic numbers are identified with the trailing +33, and in that case, the script won't run because of the ""numberFilter": "[^+]\\d+"" I assume (that's what happening when I test adding the +33 to a known spam number)

**Comment by aj3423** [comment]
> the script won't run because of the ""numberFilter": "[^+]\d+""

I haven't tested it, but I think the url `.../+33{domestic}` will work.

For people in France, there won't be the +33 when receiving a local call, it will never be +33, it can only be other country codes. All local calls are supposed to pass that numberFilter `[^+]\d+`.  IMO, your edited numberFilter is wrong.

When it sends the HTTP request, the url `.../+33{domestic}` will still work because it has already passed the number filtering step, it's just some data bytes sent to the website, which can be anything.

**Comment by dayvydrn** [comment]
> > Pesquisar nos aplicativos: telegram, whatsapp e outros (exibir lista de opções).
> 
> Tecnicamente impossível.

Link web redirect with number
