### ISSUE TITLE
v3.2 v3.1 old issue

### ISSUE THREAD

**Issue by Umotas** [aj3423/SpamBlocker#157]
I uninstall app, and re-install.
(1) New (created) WorkFlows don't save (maybe 'Save' freezed)
(2) Testing 'Read file' is not working.
 Failed: Readfile: java.io.FileNotFoundException: /storage/emulated/0/Download/spam.csv: open failed: EACCES (Permission denied)

But Import rules from file works well.

**Comment by aj3423** [comment]
1. Is the "Save" button green or grey? If it's grey, it means there is still some error with this workflow. For example: 
 - the actions can't chained together, there're red dots in between
 - if the schedule is "periodically" and the time is 00:00, which would lead to a infinite loop.
 
2. After a reinstalling, the file permission is disabled by default, you need to enable it again, by opening that workflow and click the "Save" button. When saving a workflow, it will check all permissions that required.

> But Import rules from file works well.

Manually importing rules with the sysytem file chooser is different, it doesn't require any permission, because the user is involved in this operation and the system file chooser will grant the permission for you.

**Comment by aj3423** [comment]
Ah, this is a bug.. It should be able to save a new workflow, I'll fix it later.

**Comment by aj3423** [comment]
Does it show any details about the malware?

**Comment by aj3423** [comment]
Nowadays antivirus software don't even need to tell what exactly the virus is... 
The app signing key never changes. It's the permissions introduced in v3.0, that version should've been reported malware as well.

**Comment by aj3423** [comment]
1. It will be 40 min after you press the "Save" button, I'll add a context menu item to show the next tick.
2. Will add this.

**Comment by aj3423** [comment]
Done: https://github.com/aj3423/SpamBlocker/actions/runs/11426295937

**Comment by aj3423** [comment]
Is the countdown not working? it should update every second.
Is it this action?  https://github.com/aj3423/SpamBlocker/actions/runs/11426367262ne: https://github.com/aj3423/SpamBlocker/actions/runs/11426367262

**Comment by aj3423** [comment]
Oh I see,  there is problem with the Periodically schedule.

**Comment by aj3423** [comment]
fixed: https://github.com/aj3423/SpamBlocker/actions/runs/11433765748

**Comment by aj3423** [comment]
Good idea, fixed: https://github.com/aj3423/SpamBlocker/actions/runs/11437296401
When adding a new number to the spam db, if it already exists, the timestamp will be updated.

**Comment by aj3423** [comment]
There isn't an action for deleting rules yet. 
I'll change it to not create any rule when the list is empty.

**Comment by aj3423** [comment]
done: https://github.com/aj3423/SpamBlocker/actions/runs/11453178961

**Comment by aj3423** [comment]
fixed: https://github.com/aj3423/SpamBlocker/actions/runs/11453941843
