### ISSUE TITLE
Check phone number real time

### ISSUE THREAD

**Issue by SPRATAY** [aj3423/SpamBlocker#172]
https://callfilter.app/79587290051
here is a service, there is something like a rating and comments for and against, for example, when yours call your mobile, it immediately goes to the page, quickly parses it and you receive a detailed report about this number in a notification

**Comment by aj3423** [comment]
That page exists primarily to showcase their large dataset, and currently there isn't an app that fully utilizes it. This feature is somewhat exploitative, once they become aware of it, they could easily modify the page to return a generic message like "the number is found in our database" without specifying if it's possitive or negative. Alternatively, they could limit usage to one web query per day.

It's expected to be banned, no plan for this.

**Comment by SPRATAY** [comment]
I understand your concerns, even if they find out or make a restriction, you can simply change services like gloves

I gave this as an example, you need to implement the universal parser function itself, if it is not clear I can give an example later

**Comment by aj3423** [comment]
It's not a technical problem, a generic parser isn't difficult to implement, but I don't want to do things that they don't like. I added the automated workflow because the FTC-DNC is publicly available for download, but I don't think any blocker app woud ever make their database public, that would reduce their user base.

And, not all restrictions can be easily bypassed, for example the Cloudflare verification, I don't want to get involved in this endless battle.

**Comment by SPRATAY** [comment]
no one is asking you to get involved in this battle, I just want us to have this opportunity, so that we can parse on our own and that's all, these will be our problems

or are you afraid that even with this functionality you will have problems with these companies

**Comment by aj3423** [comment]
I will only add this feature when a website officially claims that anyone can use its query service for free. I'm not going to make this app a leecher.
And again, even if it's implemted, you won't be able to use it for long.
