### ISSUE TITLE
WhiteList contacts

### ISSUE THREAD

**Issue by Tanmandal** [aj3423/SpamBlocker#199]
### The feature

A feature to block all calls even from contacts except from whitelist. I know there is a whitelist feature but it does not block other numbers present in contacts

**Comment by aj3423** [comment]
> there is a whitelist feature but it does not block other numbers present in contacts

That's because the default priority of the whitelist rule is 1, lower than the Contacts(10). 

You need two rules:
1. a blacklist rule `.*` with priority 11, it blocks all calls.
2. a whitelist rule with priority 12, it overrides the rule 1.

Check the faq for a detailed explanation about how the priority works.

**Comment by Tanmandal** [comment]
Yes it worked but the notification shows only the phone. no blocked for even saved contacts. From inside app name of contact is visible but in notification only phone number is visible. Please fix that.

**Comment by aj3423** [comment]
Fixed in the action build: https://github.com/aj3423/SpamBlocker/actions/runs/12038356348
