### ISSUE TITLE
Add phone number verification

### ISSUE THREAD

**Issue by Ilithy** [aj3423/SpamBlocker#202]
### The feature

Hi;
Would it be possible to add caller **phone number verification** (via external APIs)?

I found two _(private)_ organizations providing free keys for their number verification APIs; 
in the free version they are limited to 100 requests per month, which seems sufficient if SpamBlocker does not send requests when calling via known phone numbers _(sms or call logs and contacts)_.
It will (probably) be necessary for users to add their own keys for the APIs _(I think)_.
The information received during the analysis could be displayed in the call notification.

I do not know the extent of the complexity of integrating these APIs, but this would be an extremely useful addition, what do you think of it?

API info link:
[numlookupapi.com](https://numlookupapi.com/docs/)
[https://numverify.com/](https://numverify.com/documentation)

Thanks.

**Comment by aj3423** [comment]
Ah, since there is a free plan and it claims to support 232 countries, I'll add this feature in the next release v4.0.

Here's the proposal:

- There will be a new section "Query Online", just like the automation section, you can integrate multiple APIs. 
- It will reuse the workflow actions, they will be chained together to complete the query.
- The notification will be something like:
 "Query online: {API name} {extra info}"
for example:
"Query online: numverify telemarketers"
- Priority 0, so it will only be checked if the call has passed all other rules.
- Multi-threaded query, time out: 4 seconds(adjustable), it's limited by Android that the call screening must return within 5 seconds.

**Comment by Ilithy** [comment]
Wow, that's an extremely fast positive response, thank you very much.

Your proposal, and the various points specified are of exemplary practicality, it seems perfect to me.

With your permission, I will allow myself to check the CGU and privacy policy of these services in order to propose an update of your own privacy policy with the idea of ​​maintaining a clear approach to the possible processing of users' personal data (in case they decide to use these services, which will happen).

Thanks again.

**Comment by wildstray** [comment]
There is also another supplier for phone number verification thru APIs: https://captainverify.com/it/api-hlr.html
I cannot wait for a version with this feature!

**Comment by Ilithy** [comment]
> There is also another supplier for phone number verification thru APIs: https://captainverify.com/it/api-hlr.html I cannot wait for a version with this feature!

Thanks for this additional provider, it will be useful.
Small clarification, if I understood Aj3423's feedback on the implementation of this feature, these providers will not be added, we will have the possibility to add requests to the APIs of any provider, this is less "turnkey", but much more powerful :)

**Comment by Ilithy** [comment]
> > With your permission, I will allow myself to check the CGU and privacy policy
> 
> Yes, please, I appreciate that.

Thank to you, your application is just awesome.

I have already created a modified and clarified version (on the processing of data from third-party services), I will propose it to you when it is useful (this gives me time to refine the details)

> There will be presets for all these sites, just like the FTC-DNC workflow, import it, modify the API_KEY and it should be ready.

Thanks for the additional information; it's really great.

If I may ask a question, if (for example) one of my contacts calls me, will it pass all the rules, up to the verification(s), will it pass them?
If yes, is it possible to prevent phone numbers known by SpamBlocker from passing this (or these) verification(s)?

>I'll email the provider, asking for the approval of integrating their API in this app. I won't be adding any API without their approval, however, you should be able to compose any request you want 😏

For the approvals of the use of the apis, if they provide free access to their apis, I do not think it is necessary to ask them for this authorization, but I completely respect your decision.

an api provider to consider:
[ipqualityscore](https://www.ipqualityscore.com/documentation/phone-number-validation-api/overview)

Thanks and good night

**Comment by aj3423** [comment]
> If I may ask a question, if (for example) one of my contacts calls me, will it pass all the rules, up to the verification(s), will it pass them?

It works like this: 
All the filters are sorted by their priority in decending order, then the number will be checked by them one by one. Contacts priority is 10, if it matches a contact, the checking will stop immediately, the rest filters (including the APIs) will be skipped.
Previously I said the API priority would be 0, but on second thought, it should be -1, which means it will only be checked when it passes ALL other filters , including the blacklist rules that have priority 0.

> For the approvals of the use of the apis, if they provide free access to their apis, I do not think it is necessary to ask them for this authorization, but I completely respect your decision.

Good point. But I'll try it first to see how it goes, I guess they will allow it anyway.

**Comment by Ilithy** [comment]
> It works like this: All the filters are sorted by their priority in decending order, then the number will be checked by them one by one. Contacts priority is 10, if it matches a contact, the checking will stop immediately, the rest filters (including the APIs) will be skipped. Previously I said the API priority would be 0, but on second thought, it should be -1, which means it will only be checked when it passes ALL other filters , including the blacklist rules that have priority 0.

Thank you for your enlightening answer, and your kindness, (I am stupid, but thank you for answering...)
On the other hand, the functioning of SpamBlocker is exemplary.

> Good point. But I'll try it first to see how it goes, I guess they will allow it anyway.

I understand, I accept and respect it, I really hope for positive answers too ^^

**Comment by aj3423** [comment]
There's more work to improve the UI/translation, but the feature is ready
https://github.com/aj3423/SpamBlocker/actions/runs/12098420189

Here's the template for apilayer.net:
```json
{
    "id": 3,
    "desc": "test",
    "actions": [
        {
            "type": "ParseIncomingNumber",
            "internationOnly": false,
            "autoCC": false,
            "fixedCC": "33"
        },
        {
            "type": "HttpDownload",
            "url": "http://apilayer.net/api/validate?access_key=API_KEY&number={number}&country_code=&format=1",
            "header": ""
        },
        {
            "type": "ParseQueryResult",
            "negativeSig": "(\"valid\":false)",
            "negativeFlags": 5,
            "positiveSig": "(\"valid\":true)",
            "positiveFlags": 5,
            "categorySig": "",
            "categoryFlags": 5
        }
    ],
    "enabled": true
}
```

For numberlookup.net:
```json
{
    "id": 2,
    "desc": "",
    "actions": [
        {
            "type": "ParseIncomingNumber",
            "internationOnly": false,
            "autoCC": true,
            "fixedCC": "33"
        },
        {
            "type": "HttpDownload",
            "url": "https://api.numlookupapi.com/v1/validate/{number}",
            "header": "apikey: API_KEY"
        },
        {
            "type": "ParseQueryResult",
            "negativeSig": "(\"valid\":false)",
            "negativeFlags": 5,
            "positiveSig": "(\"valid\":true)",
            "positiveFlags": 5,
            "categorySig": "",
            "categoryFlags": 5
        }
    ],
    "enabled": true
}
```

I don't know how to test the captainverify.com, it always shows error:
> "message":"Api key not valid" 

I've tried generating new keys, but same error.

**Comment by Ilithy** [comment]
Hi;
After registration and testing (I have only tested with your internal test tool which returns me a valid response and via the API dashboard, which acknowledges receipt of requests.) it seems to work indeed, well done! and thank you very much for this quick integration!

_I have some problems with notifications which are no longer supported by Spamblocker but taken up by the respective apps, but I am not sure if this is due to SB, I will investigate a little)_

One detail, is it possible to add an option to integrate the request models added by the user (with their API keys) to the backup made by SB (manually and automatically)?

**Comment by aj3423** [comment]
Thanks for the feedback.

I forgot the backup, the API list should've been saved in the backup file, I'll fix that later. 

Not sure about the notification, I haven't changed the notification logic, if the problem still exist, please revert to the old version.

**Comment by Ilithy** [comment]
I think that, even if a version with this finalized feature is not yet released, this request can be closed as completed.
Eventually a discussion could be opened for questions related to the "query templates" to add or not to Spamblocker (if necessary), what do you think?

**Comment by aj3423** [comment]
Sure, it can be closed since the feature is ready, I have released the latest tag for people to test.

I want to ask first because previously in the matrix channel, I user recommended an API provider called PhoneBlock, he asked the auther about the integration, the reply is kinda negative, the discussion: https://github.com/haumacher/phoneblock/issues/87

Usually, modifying the URL and the http header should be enough. I've updated the help tooltip to be more straightforward. And I have sent emails to those two providers, if they agree, there will be presets, which would be even more straightforward.

**Comment by Ilithy** [comment]
Perfect, I'll close it, thanks again

I find @haumacher interventions positive in the possibility of integration and use of the API via Spamblocker, he is right to worry about setting up an automation that would have an identical calendar for all configurations; well, he did not take into account that the devices are "spread" over the different time zones.

But he does not seem against it, his first sentence proves it :)
>That sounds promising. However, I have at least one request - namely regarding the time at which the block list is retrieved. The configuration shows that a time is selected here.

>Usually, modifying the URL and the http header should be enough. 

great, Thank you for the confirmation

>I've updated the help tooltip to be more straightforward. And I have sent emails to those two providers, if they agree, there will be presets, which would be even more straightforward.

Yes I understand your decision on this point.

Thanks

**Comment by haumacher** [comment]
Hi there, 

I just wanted to confirm that I very much appreciate the integration of the PhoneBlock API into the SpamBlocker app. An on-demand number check is even much better than a regular blocklist update because it is (a) more resource efficient and (b) makes PhoneBlock aware of the activity of SPAM numbers. This allows for better tailoring of blocklists for resource-constraint devices such as Fritz!Box routers.

On my whishlist is also a feature, where a user that was called by a SPAM nuber not yet on the blocklist can easily report that number to PhoneBlock via its API. Is this already possible?

Best regard Bernhard

**Comment by aj3423** [comment]
@haumacher I appreciate the clarification.
Then I'll add PhoneBlock to the presets, only on-demand check, no database downloading.

Number reporting isn't supported yet, but it's on the plan. When it's done, I'll add PhoneBlock to the presets as well.

Thank you and best regards.

**Comment by Ilithy** [comment]
Good evening;

In order to limit unnecessary requests to third-party services, would it be possible to add an action to the instant query workflow?
this action could, if the database return finds a match _(with, perhaps, the choice of the type of match, for example spam -> add to db, marketing -> do not add)_, the test number could be automatically added to the user's spam database.
do you think this is feasible and useful?

**Comment by aj3423** [comment]
Good evening.

> would it be possible to add an action to the instant query workflow?

Good idea, so if the number calls the second time, it will be blocked directly by the database without querying online again. I'll add this.

However, I think the number should be added to the database as long as it's blocked. The category (spam or marketing) should be used to check whether to block or not, which is identified by the "negative identifier".

**Comment by Ilithy** [comment]
Hi
>so if the number calls the second time, it will be blocked directly by the database without querying online again. I'll add this.

Hi;
That is exactly what I think. :)
Thank you very much for considering this request.

>However, I think the number should be added to the database as long as it's blocked. The category (spam or marketing) should be used to check whether to block or not, which is identified by the "negative identifier".

I understand, you're completely right on this point.

**Comment by Ilithy** [comment]
Hi
I tested this template, it works perfectly, and [Ipqualityscore](https://www.ipqualityscore.com/) offers 1000 requests per month for free (24 per day).
Thanks

```
{
    "id": 4,
    "desc": "ipqualityscore",
    "actions": [
        {
            "type": "ParseIncomingNumber",
            "internationOnly": false,
            "autoCC": false,
            "fixedCC": "33"
        },
        {
            "type": "HttpDownload",
            "url": "https://www.ipqualityscore.com/api/json/phone/API_KEY/{number}?country[]=FR",
            "header": ""
        },
        {
            "type": "ParseQueryResult",
            "negativeSig": "(\"valid\":false)",
            "negativeFlags": 5,
            "positiveSig": "(\"valid\":true)",
            "positiveFlags": 5,
            "categorySig": "",
            "categoryFlags": 5
        }
    ],
    "enabled": true
}
```

**Comment by aj3423** [comment]
Nice. 
I'm trying to add the feature number reporting, which will only report numbers that are blocked by local rules, not those blocked by APIs. Because the numlookup has replied to my email, they don't want their numbers to be leaked to competitors. I think reporting local numbers should be fine, in this case, maybe those API providers would be happy with the integration, and there would be more presets, I suppose.

**Comment by Ilithy** [comment]
> Nice. I'm trying to add the feature number reporting, which will only report numbers that are blocked by local rules, not those blocked by APIs. Because the numlookup has replied to my email, they don't want their numbers to be leaked to competitors. I think reporting local numbers should be fine, in this case, maybe those API providers would be happy with the integration, and there would be more presets, I suppose.

Hi;
It's really a shame but to be honest it's understandable, it goes against their interests (the more you use the API, the more likely it is that you'll end up taking a paid plan), but by checking their CGU (T&C) it doesn't violate them (it stays on the device, and is not transmitted to any third party).

but you have decided, I respect your decision.
Thank you very much for the work you do, and for following up on requests, it's really great of you.

**Comment by Ilithy** [comment]
Ok cool, this still gives me hope ;)
Thanks for the precision.

```
{
    "id": 5,
    "desc": "abstract",
    "actions": [
        {
            "type": "ParseIncomingNumber",
            "internationOnly": false,
            "autoCC": false,
            "fixedCC": "33"
        },
        {
            "type": "HttpDownload",
            "url": "https://phonevalidation.abstractapi.com/v1/?api_key=API_KEY&phone={number}",
            "header": ""
        },
        {
            "type": "ParseQueryResult",
            "negativeSig": "(\"valid\":false)",
            "negativeFlags": 5,
            "positiveSig": "(\"valid\":true)",
            "positiveFlags": 5,
            "categorySig": "",
            "categoryFlags": 5
        }
    ],
    "enabled": true
}
```

This templates work for Abstract API validation and verification, limited on the free plan to 250 calls per month (at a rate of one check per second).

**Comment by haumacher** [comment]
> Good idea, so if the number calls the second time, it will be blocked directly by the database without querying online again. I'll add this.

Let me point out the PhoneBlock perspective to this approach: A SPAM number database such as PhoneBlock requires user reports about SPAM calls to decide about the activity of a SPAM number. If you enter a number that was found to be SPAM to your local database, then there is no chance for the shared SPAM database to further observe activity of this number - every user makes at least a single lookup for a certain number. 

For PhoneBlock, it is critical to observe the activity of SPAM numbers to keep active numbers while dropping inactive ones. This database cleanup is especially required, to deliver block lists to resource constraint devices such as Fritz!Box routers. In those block lists, only the most active numbers must be included since there is a limit of 2000 numbers to the block list.

When you enter a number found to be SPAM to the local device database (to reject the call fast without network lookup), it would be very useful for the community, if you report this blocked call to the PhoneBlock database - just to keep the number active there.

**Comment by haumacher** [comment]
> One thing I forgot to mention that, both querying and reporting are optional in SB, they will not be forced to be enabled. For example, a user can choose to enable the number query API, but he doesn't want to report any number, would you be okay with this?

This if fine for me. Would be cool, if you could explain users, why reporting is essential for the system to work. But if somebody still does not want to report, this is OK.

**Comment by aj3423** [comment]
> if you could explain users, why reporting is essential for the system to work.

I will explain to the user that this is important to the community driven services.

**Comment by aj3423** [comment]
Oh, I just found that, it's actually a bit complicated about the SPAM db, numbers logged in the SPAM db are actually blocked by APIS in the first place, so they shouldn't be reported. I'll try to find a way to solve this..

**Comment by browntownington** [comment]
Would it be possible to have the Positive Indentifier (allow) take a priority over the Negative Indentifier (block)?

I've written a pretty juicy regex for ipqualityscores which essentially matches anything sus including particular telco's.

The Negative Identifier is:

"valid":false|"fraud_score":(?!0\b)\d+|"(recent_abuse|VOIP|risky|spammer)":(true)|"active":false|"carrier":\s*"(.*?\b(?i:symbio|chime|primus)\b.*?)"(?=\s*,)

I wanted to use the Postive Intendifier as a means to make exceptions to the Negative Indentifier. For example I may receive trusted calls voip from a telco called telco1 where they have high fraud score and deemed risky.

"carrier":\s*"(.*?\b(?i:telco1)\b.*?)"(?=\s*,)


I realise I could create another query and use the positive indentifier to allow. However I can't seem to find in the UI how to put a priority order so that the allow is triggered first.

What's the best approach to handle this situation?

**Comment by aj3423** [comment]
@browntownington I don't want to add an option for this because it's a rare use case. Instead, I made the action `ParseQueryResult` chainable, so you can add two `ParseQueryResult` actions like:

- Intecept Call
- HTTP Request
- Parse Result  (negative, with that really juicy regex)
- Parse Result (positive, telco1)
- Filter Spam
- Add to Spam DB

It's a bit counterintuitive that you might expect the first to have higher priority, but actually the actions are executed in order, so the next output will overrede the previous one.

done in the action build: https://github.com/aj3423/SpamBlocker/actions/runs/14418941126

**Comment by browntownington** [comment]
@aj3423 that's fair. The method you proposed would do the job!

Appreciate you looking at it. I just downloaded and tested the action build. It's complaining that the number wasn't parsed and the api response is obviously providing null values. I'll attach a screenshot. Am I doing something wrong here?

**Comment by aj3423** [comment]
@browntownington Ah I missed that test case, it's fixed: https://github.com/aj3423/SpamBlocker/actions/runs/14419592745
As in the image, the testing log will always shows two results, but the latter will override the former.

**Comment by browntownington** [comment]
@aj3423 I'm not sure what you changed between the two action builds. I retested again this morning and I had infact missed a digit in my test number and therefore the output was correct about the invalid number. With a correct test number both action builds worked exactly as expected. Appreciate you implementing this 🍻

**Comment by aj3423** [comment]
> I'm not sure what you changed between the two action builds.

The previous one supports "positive" and "negative", but not "unidentified". It's fixed in the latter build.
