### ISSUE TITLE
Add statistics for blocked requests

### ISSUE THREAD

**Issue by ghost** [aj3423/SpamBlocker#212]
### The feature

It would be nice to view statistics on the amount of blocks per rule and/or the total.
The idea would be to show a blocked icon and the amount of blocked items.

I made a fast (and bad) sketch to show how it could look like for the regex rules.
![image](https://github.com/user-attachments/assets/fbbe4c70-f81d-4e53-b301-c6e9b4a13a8b)

For the total amount of blocked items I would not exactly know where to put it, maybe someone has a suggestion?
Furthermore it could be an interesting to show a graph with the amount of blocks per day/week/month on a different tab.

**Comment by aj3423** [comment]
No plan for this. Every line of code in this app is dedicated to blocking calls, this feature is not.
Let's say these two rules in the image, rule 1 has a score of 1000 and rule 2 has never blocked any call yet, you won't delete rule 2 just because its score is 0, so the score doesn't really matter.
