### ISSUE TITLE
Switch to Material You design

### ISSUE THREAD

**Issue by ghost** [aj3423/SpamBlocker#214]
### The feature

Material You allows for personalization by adapting a user's system colors into the design.
For example Obtainium has a setting that changes the application color based on the defined system colors.
Material You also allows a consistent user experience across devices, which improves usability and navigation.

**Comment by aj3423** [comment]
No plans for this, I agree that the Material looks beautiful, but its elements tend to be larger, and rounded corners can consume more space than square corners. The app is supposed to show lots of elements in a single screen, with a high widget density.

Actually the app already uses Material 3 widgets, but I re-implemented most of them(SwitchBox, TextBox, BottomBar...). I guess even afetr switching to MaterialYou, I would still re-implement them and the UI would look exactly the same.

However, the theme colors, particularly in the light theme, still need improvement. The current contrast level is too high. Because I only use the dark theme. Contributions to the colors are welcome.
