### ISSUE TITLE
Use application activities to judge a call

### ISSUE THREAD

**Issue by SpectureCarrier** [aj3423/SpamBlocker#218]
### The feature

Whether it is possible to support the use of specific application activity on foreground to judge whether a call is being rejected or received, because an app is usually not only used for making or receiving calls.

**Comment by aj3423** [comment]
I don't understand, especially for this: 
> because an app is usually not only used for making or receiving calls.

Can you show me a use case?

**Comment by aj3423** [comment]
I still don't understand. Let's say you are using WhatsApp, when it's in the foreground, you want all calls to be allowed? Why is that?

**Comment by aj3423** [comment]
I guess you not using the latest version, now there is the Meeting Mode, which does exactly what you need, calls will be rejected during online video conferences.

**Comment by aj3423** [comment]
It's checking if the app is running a foreground service, which it's more accurate than checking activity, this approach should work for any apps.

**Comment by aj3423** [comment]
No , it's won't reject calls when the app is opened. It won't regret calls even when you are typing messages. It will only reject calls during a video meeting.

**Comment by aj3423** [comment]
I guess you don't really understand what a foreground service is, please try this feature, It should work as expected.

**Comment by aj3423** [comment]
Let me explain a bit, the "foreground service" is not just "the app is running in the foreground".  

It's an Android service, when an app starts a video meeting, It will start a service to keep the app alive, usually there will be a notification that can't be deleted, if you delete it, It will appear again later. This service is what I meant by the foreground service. 

When you just opened the app, or typing messages, It won't start such device, because it's a necessary and such service would consume more battery. However, when the video meeting is started, it's will appear in the notification, which means the foreground service is started.

**Comment by aj3423** [comment]
Which app will reject all calls where it's just started?

**Comment by aj3423** [comment]
I remember that checking foreground activity is restricted by Android, not very sure. I'll find a way to solve this.

**Comment by aj3423** [comment]
Activity is the last option, it's unreliable, it can be overlapped or minimized, and it's more difficult to implement. FG service on the other hand, is better in all aspects.

FG services also have names, the app now allows you to enter some services names to exclude.

Done in the action build: https://github.com/aj3423/SpamBlocker/actions/runs/12233459161

**Comment by aj3423** [comment]
I'll add the "click to add the name" in the next release.
