### ISSUE TITLE
US incoming numbers add '1', contacts ignored

### ISSUE THREAD

**Issue by gufstersonian** [aj3423/SpamBlocker#57]
Hello. First thank you for a great application. This is amazing. On my phone (Pixel/GrapheneOS) in the US (AT&T), incoming calls have a leading '1'. My contacts do not have that '1', so the Contacts filter does not allow them. I added a '1' to one of my contacts and it worked after doing so. Is there a way to allow for the leading '1' (so I do not have to add '1' to every one of my contacts)? Or, am I looking at this the wrong way?

Again, thank you for providing this.

**Comment by gufstersonian** [comment]
Mine show up as +12223334444. The '+' appears to be ignored as expected, but an example number in my contacts is (222) 333-4444. If I change the contact number to 1 (222) 333-4444 it works. I have Contacts/inclusive on with a rule '.*' with priority 1. I would think other people would have this problem so maybe I am doing something wrong.

**Comment by aj3423** [comment]
The number `+12223334444` should have been allowed, I just tested this number with contact `2223334444` and it worked. Which version are you using?

**Comment by gufstersonian** [comment]
I installed v1.7 from the release page - that version works as expected. Thank you!

**Comment by vertuk** [comment]
Thank you very much! The `1.7` update has also fixed a similar issue with Russia/Kazakhstan +7 prefix. The thing is it's also possible to use an 8 instead of +7 (just an 8 without a '+') and both these versions are accepted by phones and carriers interchangeably, so we save numbers with 8 too. 
But if we used to set the SpamBlocker filter rules to block calls not from the contacts list, the numbers in the contacts that start with 8 instead of +7 have actually been getting blocked because they didn't coincide with the number that appeared to be calling, which is always an identical number that starts with +7.

Now it's resolved, thanks again!
