### ISSUE TITLE
Google Play Protect detect SpamBlocker as a malicious app since v1.7 release

### ISSUE THREAD

**Issue by djelloul78** [aj3423/SpamBlocker#58]
Bonjour, 

I'm opening this issue but it's not really something related to a malfunction or an enhancement request.

I've just installed last published release (v1.7) on F-Droid this morning and I have been warned by Google Play Protect that your app is dangerous to be installed.
It makes the app considered malicious and I see regular notifications on Google Play Store requesting to uninstall your app. 

I reverted back to v1.5 and no more alert was raised anymore.
Same with v1.6, no warning alert.
But as soon as I try to install v1.7, warnings and alerts come back.
I have made the same exercise with GitHub releases and conclusions are the same.

It seems something doesn't fit Google Play Protect rules, probably for something in which it overreact, but I think you should take a look about this aspect.
Many SpamBlocker users comes from "Yet Another Call Blocker" app that ended with the same Google Play Protect restrictions but it isn't maintained anymore (no update since more than 3 years) and some users are afraid of using it because of these alerts and warnings.

It will be sad if your app ends with less success than it deserves just because some GAFAM group has decided that your app doesn't follow their SW specification...

I don't think there's any emergency or mandatory request to update the app according to this remark.
Consider this message more as a notification that can explain why there could be less download or user of your app in the next months.

What do you think? 

Thank you for your attention.

**Comment by aj3423** [comment]
Thanks for the feedback. I can reproduce this with v1.7. 
This is strange, these releases had been tested on my phone, but I didn't see that warning previously. And I just tested with the latest tag which was built yesterday and there is no warning, I haven't removed any feature or permission, only added more features. 
Maybe because the v1.7 is now released on F-Droid, and Google verifies apps on F-Droid, only this can explain everything. I think a workaround is to publish this on Play Store as well (is google forcing devs to publish apps on Play Store?...)

I'll keep an eye on the next v1.8, see if it becomes malicious right after F-Droid merges it. For the v1.7, I'll try every commit to find out which one causes the problem, it worn't help if the warning is based on apk signature, but I'll try it anyway.

**Comment by djelloul78** [comment]
Don't stress yourself for Google publishing...
F-Droid is an alternative that fits people looking for another way to use their devices in compliance with open source solutions and make the link between us and talented people as you are.

If Google does restrict some external app to be part of their store, why not. 
But blaming an app being malicious with no evidence of that, it's another story that I really don't appreciate.

Keep up the good job!

**Comment by aj3423** [comment]
I also install these releases on my phone, I'm the first one who installed them, but I've never seen any popup at the time. 

I just tested v1.7, v1.8, and latest version on two phones with different google accounts (different countries)
- v1.7 shows popup warning on one phone but not the other
- v1.8 and latest version, no popup at all

But my popup shows "it's harmful and blocked", not "the app is unknown from its database and it needs to be scanned".

Maybe it's also based on country or device, I'm a bit confused. But since all issues have been completed, I'm working on publishing to play store.

**Comment by aj3423** [comment]
It's incredibly complex to publish an app on Google Play, it took even longer than developing this app, but finally it's live.

https://play.google.com/store/apps/details?id=spam.blocker

**Comment by aj3423** [comment]
Well, Google exposes the personal information of individual developers. For my privacy, I unpublished this app, let's just ignore that installation warning :)
