### ISSUE TITLE
Really blocking calls?

### ISSUE THREAD

**Issue by davidpiano** [aj3423/SpamBlocker#60]
I would love to have real call blocking, the way it worked many years ago. But does this app really stop callers from connecting, or does it only stop my phone from ringing?

The most obvious difference is that when a call is truly blocked, it's impossible for the caller to leave a message. It also means the caller will never know if my number exists, because they are rejected **before** being allowed to connect, not after.

**Comment by aj3423** [comment]
The call is not truly blocked, it's just rejected, as if being manually rejected by pressing the "reject" button.

**Comment by djelloul78** [comment]
Bonjour davidpiano,

I'm surprised by your expectation based on an app.
As soon as the app filters calls that reaches the phone, you'll have no other choices than managing it manually or automatically with what your phone network provider delivers.

For my own culture, can you share how you were blocking phone numbers many years ago?

From my knowledge perspective, if you'd like a phone to be blocked before it reaches your device, it has to be filtered at network level not device level.
I remember very long time ago that we had such type of blocking feature using phone codes on fixed home phones but it wasn't ported on mobile services in my country. 
There was very few service that were maintained on French mobile networks.
I remember I was able to disable/enable voicemail using a phone code, allowing me to never miss a call due to slowliness...

We still have such network level services active but they are very limited today (show phone number, call transfer, forbidden outgoing calls, etc...), however they're maybe still existing in you country area.
You can have a look on that from your phone by checking additional parameters. 
They'll be listed in a very slow manner because it's a negotiation between your phone and the network provider to list all available ones and their setting options. 

Additionally, I have an SIP phone number that I use when I'm foreign traveling or when I want to drop someone to a phone line that I never consult...
It can be managed at network level from a web interface and I can do everything from there.
For example, I can deactivate the phone line to react to any call or just some phone numbers and decide to not allow these numbers to end in a voice mail or make the phone ringing at all as if the phone number was wrong or not attributed.
You maybe have something similar as this configuration center available but for mobile phone lines?

Waiting for your answer as I'm interested in how things were managed from your side. 

Thank you for your attention.

**Comment by happydude** [comment]
I think the way they used to do it was the filter app would answer the call and then immediately hang up, that way the caller never got sent to voicemail.

**Comment by aj3423** [comment]
> I think the way they used to do it was the filter app would answer the call and then immediately hang up, that way the caller never got sent to voicemail.

Interesting approach, I've been googling for a while, tried apps like AutoAnswer and MotoAnswer, none of them works, tested on Android 10 and 14, it's just ringing and not get answered.

Please let me know if there is any app that actually works, no matter opensource or not.

**Comment by davidpiano** [comment]
I was talking about **much older** forms of call blocking, which truly did stop unwanted callers from successfully dialing your number. The caller would get only a phone company's recorded message "We are sorry, your call could not be completed" or that type of thing.

I believe (at least where I am) this older and better kind of call blocking does not exist anymore, and it has probably been gone for a long time. But when I read the description here, it gave me hope - for a moment. :)

**Comment by pearlheartgtr** [comment]
The best call blocker ever was the one built into the Cyanogen Mod roms. The next best was Calls Blacklist Pro. Both blocked anything not in your contacts from calls and texts. Calls would get rejected and you could have them sent to voicemail or just hang up. But either way, you didn't get notifications.

**Comment by aj3423** [comment]
Now it's supported in the latest tag, the `Silence Call` has been replaced with `Block Mode`, with a new mode "Answer and Hang up", also available in the per rule setting.

**Comment by aj3423** [comment]
It works perfectly on android 10 emulator, but on android 14 it behaves randomly, I'm trying to figure out why, plz use other block type for now.

**Comment by aj3423** [comment]
Now it should work, but there are drawbacks:
 - the lockscreen will be turned on for a while
 - it plays a call end tone, some phones have options to mute this sound.
 - vibration, this can be disabled in system settings.

I can't find a way to solve them programmatically, this seems to be the closest to the "real blocking", I'm closing this for now.
