### ISSUE TITLE
[suggestion] paid playstore version

### ISSUE THREAD

**Issue by redcat42** [aj3423/SpamBlocker#64]
I appreciate and love the app.

I used to develop apps a long time ago, after sometime, it becomes hard to stay motivated, I suggest making a paid play store version of the app

this way, people like me, who want to support your work, can buy the app, also, we can leave feedback and rating which will motivate you to keep the app updated 

this is just a suggestion, I'm not implying you need money or anything like that 

I hope you take what I'm saying in the right spirit

thanks for all your work

**Comment by aj3423** [comment]
Thanks for your support!
I'm well motivated by the spammers, previously I got my nerve hurt and it was too painful to sleep, for two months I got fucked really hard by the spamers, that made my determination to write this app. I plan to release it as FOSS on PlayStore once it's fully developed, the app itself will always be FOSS, I'll put a "buy me a coffee" on the github page for anyone who wants to show their support. 
Luckily, with AI tools available, adding new features is getting a lot easier, since I use this app daily, I expect to maintain it or a long time, good ideas are always welcome.
Cheers.
