### ISSUE TITLE
Please, add Spanish translation (es)

### ISSUE THREAD

**Issue by Neebly** [aj3423/SpamBlocker#75]
Greetings.

First of all, thank you so much for this fantastic app!

On the other hand, would you mind providing a Spanish translation, please?

Thank you again for your work and your time!

**Comment by aj3423** [comment]
Done in this action build: https://github.com/aj3423/SpamBlocker/actions/runs/9489868059

**Comment by Neebly** [comment]
> Done in this action build: https://github.com/aj3423/SpamBlocker/actions/runs/9489868059

Quite decent.
Thanks!

**Comment by aj3423** [comment]
It shows "Copy" when the text in the inputbox is exactly the same as the current json configuration(including the language), because importing a same configuration would be unnecessary.
When the language is changed, the current configuration becomes different, then it shows "Import".
To force import a configuration, you can add a space somewhere to make the text different, or export/import as compressed format.

**Comment by Neebly** [comment]
Oh, that makes sense.
Thanks, and sorry for wasting your time!
Have a nice weekend.
