### ISSUE TITLE
Long sms "passed by default" again in v1.13

### ISSUE THREAD

**Issue by wdlid** [aj3423/SpamBlocker#77]
Here is the sms:

【特斯拉中国】尊敬的客户您好，诚邀您参与本次调研，我们始终致力于提升您的体验，您的反馈对我们至关重要。本次调研大概占用1-3分钟的时间，感谢支持！
问卷链接：https://cx.tesla.cn/q/ZXPSM5Y5 拒收请回复R

and the block words is

.*(交通委|联合会|林业局|信息化部|拒收请|拒收回).*

after deleting the url part, it will be correctly matched.

Thanks so much.

**Comment by aj3423** [comment]
There should be asterisk after the dot: 
`.*` instead of `.`

I tried regex `.*(交通委|联合会|林业局|信息化部|拒收请|拒收回).*` and the content is blocked correctly.

**Comment by wdlid** [comment]
sorry github eat my asterisk, I have this symbol actually.
![Screenshot_20240616_101932_SpamBlocker](https://github.com/aj3423/SpamBlocker/assets/12636756/d4a71198-1467-484b-ac2f-6ff0d9953bf0)
![Screenshot_20240616_102041_SpamBlocker](https://github.com/aj3423/SpamBlocker/assets/12636756/d9de2e97-285f-4d12-b31a-52730f2f3aeb)

**Comment by wdlid** [comment]
For comparison 

![Uploading Screenshot_20240616_102701_SpamBlocker.jpg…]()

**Comment by aj3423** [comment]
It's caused by the regex flags, to be more specific, the `d` prefix. By default, these flags are enabled and not displayed, in your case they are disabled.

`.*` doesn't work with multiline content without the flag "Dot Match All" . I guess the previous spam messages only contain single line content, so they didn't trigger this problem.

You don't need that flags, they are disabled by some historical reason(upgraded from an ancient version), you can check these checkboxes and the problem should be solved:
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/21cc757e-163c-4f70-8ac0-d8ced82fa013)

**Comment by wdlid** [comment]
Thanks for the quick response💕
That is the root cause~
