### ISSUE TITLE
App Ideas

### ISSUE THREAD

**Issue by bb1a2** [aj3423/SpamBlocker#84]
Hi,

Since SB matured nicely 👍, I thought I'd ask you if you are open to other app ideas. I have a few in mind. In most cases there was an app but it hasn't been updated in years (Some of them are FOSS while others are not).
- Most of these apps are unique/rare in their functionality.
- There is almost no good FOSS (or even a well-behaved freeware) alternative.

I can provide examples of the apps of course if you are interested.

Thanks

**Comment by aj3423** [comment]
Actually I'm not interested in writing more apps, I'm not an android developer at all.. I wrote SB because a couple of months ago I was sick and couldn't sleep, whenever I got a bit sleepy I got shocked up by a spam call, that made me determined to write a call blocker. When I got recovered, I learned android dev from scratch and wrote SB.

I'll always maintain SB, but no more new apps I guess :)

**Comment by bb1a2** [comment]
I see. No problem. Thanks for the great app.
