### ISSUE TITLE
Package name instead of "spam.blocker"

### ISSUE THREAD

**Issue by 2k1dmg** [aj3423/SpamBlocker#93]
Hi, I think the package name should be, for example, "com.aj3423.spamblocker" instead of "spam.blocker".

**Comment by aj3423** [comment]
Thanks for the suggestion. I understand there are a couple of reasons for this naming convention:

- Package organization
  Not a problem to this app.
- Uniqueness
  Since no one else would use name like spam.blocker, this name is actually unique.
- Bandwagon
  People all do so, but I'm not a guy of following standard, more willing to break it.

It's concise and to the point, no redundant words, I'll only rename it when it becomes a real trouble.
