### ISSUE TITLE
Integrate spam number database

### ISSUE THREAD

**Issue by advait404** [aj3423/SpamBlocker#96]
Hi,
It would be great if the app can also optionally add spam number databases and block/silent numbers present there.

Eg database:

https://www.ftc.gov/policy-notices/open-government/data-sets/do-not-call-data

**Comment by advait404** [comment]
The other top Foss alternatives for spam blocking do use existing databases as well. I think finding one or more good databases and integrating them will make this a great feature to add.

https://f-droid.org/packages/us.spotco.carrion/

https://f-droid.org/packages/dummydomain.yetanothercallblocker/

**Comment by aj3423** [comment]
There are a couple of reasons that I don't want to integrate databases.

- They target different audiences:
  1. Exclusive, for people who are more inclined to reject unknown calls, since they block all unknown numbers, a database would be redundant. 
  2. Inclusive, for people like salesmen who need to pick unknown calls to get new clients, they would prefer the database solution, and they don't need features in SpamBlocker.
  
  In my opinion, SpamBlocker and database actually conflict.
- Too many databases in different countries, their API may change from time to time, the maintenance would be an endless job. 
- There is now a feature "import blacklist from file", you can download the csv and import it manually, it'll be available in the next release.
- Actually I think google should support chain of call screening, for example, when a call passes SpamBlocker, it's then checked again by some other blockers that based on database, a call would only pass when it passes all screening apps. So all different screening apps can work together with their functionality kept simple.

**Comment by aj3423** [comment]
There is a plan now: https://github.com/aj3423/SpamBlocker/issues/140
